version: '3.9'
services:
  backend:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongodb 
  frontend:
    build:
      context: ./UniMaterial
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    depends_on:
      - mongo-seed
  mongo-seed:
    image: mongo:latest
    volumes:
      - ./recursos.json:/datasets/dataset.json
    command: mongoimport --host mongodb -d material -c recursos --type json --file /datasets/dataset.json --jsonArray