
version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    depends_on:
      - mongo-seed
  mongo-seed:
    image: mongo:latest
    volumes:
      - /mnt/c/Users/pedro/OneDrive/Ambiente de Trabalho/3ano/2sem/EngWeb/EngWeb2024/Projeto/projetoEngWeb/recursos.json:/datasets/dataset.json
    command: mongoimport --host mongodb -d material -c recursos --type json --file /datasets/dataset.json --jsonArray
